### ISSUE TITLE
example-app: unable to start app & ci build fails

### ISSUE THREAD

**Issue by takahser** [angular-redux/platform#43]
see Circle CI build: https://circleci.com/gh/angular-redux/example-app

also, when trying to run the example app locally (`npm install && ng serve`), it fails:

```
ERROR in /Users/sta/repo/angular-redux-platform/packages/example-app/node_modules/@angular-redux/store/lib/src/components/root-store.d.ts (13,35): Generic type 'Reducer' requires 1 type argument(s).
ERROR in /Users/sta/repo/angular-redux-platform/packages/example-app/node_modules/@angular-redux/store/lib/src/components/ng-redux.d.ts (25,44): Generic type 'Reducer' requires 1 type argument(s).
ERROR in /Users/sta/repo/angular-redux-platform/packages/example-app/node_modules/@angular-redux/store/lib/src/components/ng-redux.d.ts (42,82): Generic type 'Reducer' requires 1 type argument(s).
ERROR in /Users/sta/repo/angular-redux-platform/packages/example-app/node_modules/@angular-redux/store/lib/src/components/observable-store.d.ts (37,73): Generic type 'Reducer' requires 1 type argument(s).
ERROR in /Users/sta/repo/angular-redux-platform/packages/example-app/node_modules/@angular-redux/store/lib/src/components/fractal-reducer-map.d.ts (9,60): Generic type 'Reducer' requires 1 type argument(s).
ERROR in /Users/sta/repo/angular-redux-platform/packages/example-app/node_modules/@angular-redux/store/lib/src/components/fractal-reducer-map.d.ts (9,86): Generic type 'Reducer' requires 1 type argument(s).
ERROR in /Users/sta/repo/angular-redux-platform/packages/example-app/node_modules/@angular-redux/store/lib/src/components/fractal-reducer-map.d.ts (11,86): Generic type 'Reducer' requires 1 type argument(s).
ERROR in /Users/sta/repo/angular-redux-platform/packages/example-app/node_modules/@angular-redux/store/lib/src/components/fractal-reducer-map.d.ts (13,87): Generic type 'Reducer' requires 1 type argument(s).
ERROR in /Users/sta/repo/angular-redux-platform/packages/example-app/node_modules/@angular-redux/store/lib/src/decorators/helpers.d.ts (21,19): Generic type 'Reducer' requires 1 type argument(s).
ERROR in /Users/sta/repo/angular-redux-platform/packages/example-app/node_modules/@angular-redux/store/lib/src/components/ng-redux.d.ts (40,44): Generic type 'Reducer' requires 1 type argument(s).
ERROR in /Users/sta/repo/angular-redux-platform/packages/example-app/node_modules/@angular-redux/store/lib/src/components/root-store.d.ts (13,101): Type 'Middleware' is not generic.
ERROR in /Users/sta/repo/angular-redux-platform/packages/example-app/node_modules/@angular-redux/store/lib/src/components/root-store.d.ts (13,157): Generic type 'StoreEnhancer' requires 1 type argument(s).
ERROR in /Users/sta/repo/angular-redux-platform/packages/example-app/node_modules/@angular-redux/store/lib/src/components/root-store.d.ts (14,27): Generic type 'Store<S>' requires 1 type argument(s).
ERROR in /Users/sta/repo/angular-redux-platform/packages/example-app/node_modules/@angular-redux/store/lib/src/components/root-store.d.ts (17,35): Generic type 'Reducer' requires 1 type argument(s).
ERROR in /Users/sta/repo/angular-redux-platform/packages/example-app/node_modules/@angular-redux/store/lib/src/components/root-store.d.ts (20,80): Generic type 'Reducer' requires 1 type argument(s).
ERROR in /Users/sta/repo/angular-redux-platform/packages/example-app/node_modules/@angular-redux/form/dist/source/compose-reducers.d.ts (2,60): Generic type 'Reducer' requires 1 type argument(s).
ERROR in /Users/sta/repo/angular-redux-platform/packages/example-app/node_modules/@angular-redux/form/dist/source/compose-reducers.d.ts (2,92): Generic type 'Reducer' requires 1 type argument(s).
ERROR in /Users/sta/repo/angular-redux-platform/packages/example-app/node_modules/@angular-redux/form/dist/source/form-reducer.d.ts (3,194): Type 'Action' is not generic.
ERROR in Error: Metadata version mismatch for module /Users/sta/repo/angular-redux-platform/packages/example-app/node_modules/@angular-redux/store/lib/src/index.d.ts, found version 4, expected 3, resolving symbol AppModule in /Users/sta/repo/angular-redux-platform/packages/example-app/src/app/module.ts, resolving symbol AppModule in /Users/sta/repo/angular-redux-platform/packages/example-app/src/app/module.ts
    at syntaxError (/Users/sta/repo/angular-redux-platform/packages/example-app/node_modules/@angular/compiler/bundles/compiler.umd.js:1729:34)
    at simplifyInContext (/Users/sta/repo/angular-redux-platform/packages/example-app/node_modules/@angular/compiler/bundles/compiler.umd.js:24979:23)
    at StaticReflector.simplify (/Users/sta/repo/angular-redux-platform/packages/example-app/node_modules/@angular/compiler/bundles/compiler.umd.js:24991:13)
    at StaticReflector.annotations (/Users/sta/repo/angular-redux-platform/packages/example-app/node_modules/@angular/compiler/bundles/compiler.umd.js:24418:41)
    at _getNgModuleMetadata (/Users/sta/repo/angular-redux-platform/packages/example-app/node_modules/@angular/compiler-cli/src/ngtools_impl.js:138:31)
    at _extractLazyRoutesFromStaticModule (/Users/sta/repo/angular-redux-platform/packages/example-app/node_modules/@angular/compiler-cli/src/ngtools_impl.js:109:26)
    at Object.listLazyRoutesOfModule (/Users/sta/repo/angular-redux-platform/packages/example-app/node_modules/@angular/compiler-cli/src/ngtools_impl.js:53:22)
    at Function.NgTools_InternalApi_NG_2.listLazyRoutes (/Users/sta/repo/angular-redux-platform/packages/example-app/node_modules/@angular/compiler-cli/src/ngtools_api.js:91:39)
    at AotPlugin._getLazyRoutesFromNgtools (/Users/sta/repo/angular-redux-platform/packages/example-app/node_modules/@ngtools/webpack/src/plugin.js:240:66)
    at _donePromise.Promise.resolve.then.then.then.then.then (/Users/sta/repo/angular-redux-platform/packages/example-app/node_modules/@ngtools/webpack/src/plugin.js:493:24)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:182:7)

```

My environment:

```
ng version
Your global Angular CLI version (6.0.7) is greater than your local
version (1.7.3). The local Angular CLI version is used.

To disable this warning use "ng config -g cli.warnings.versionMismatch false".

    _                      _                 ____ _     ___
   / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
  / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
 / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
/_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
               |___/
    
Angular CLI: 1.7.3
Node: 9.11.1
OS: darwin x64
Angular: 4.4.7
... common, compiler, compiler-cli, core, forms, http
... platform-browser, platform-browser-dynamic, router
... tsc-wrapped

@angular/cli: 1.7.3
@angular-devkit/build-optimizer: 0.3.2
@angular-devkit/core: 0.3.2
@angular-devkit/schematics: 0.3.2
@ngtools/json-schema: 1.2.0
@ngtools/webpack: 1.10.2
@schematics/angular: 0.3.2
@schematics/package-update: 0.3.2
typescript: 2.9.2
webpack: 3.11.0
```

**Comment by qbq** [comment]
I met same issue, any solution?

**Comment by smithad15** [comment]
We are in the process of doing a much needed tooling upgrade to the example app. Please see #8 for progress
